//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyAway
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class AeroportOfficiel
    {
        //[Key]
        public int Id { get; set; }
        public string Pays { get; set; }
        public string Aeroport { get; set; }
        public string Ville { get; set; }

        public AeroportOfficiel(string pays, string aeroport, string ville)
        {
            Pays = pays;
            Aeroport = aeroport;
            Ville = ville;
        }
    }
}
